### PR TITLE
Update the frequency and wait time

### PR DESCRIPTION
**Pull request by belak**
This is based off of a similar PR which went into QMK. The same improvement may be possible to make in other places as well.

https://github.com/jackhumbert/qmk_firmware/pull/866

I'm still testing this change, but it should work fine.

### CODE REVIEW

**Comment by tmk** [comment]
Thank you for the patch.

I also found and looked into this `wait_us()` issue the other day, after reading Chibios discussions and resources on line I decided to implement 'NOP loop wait' for the wait function like AVR Libc does.
http://www.chibios.com/forum/viewtopic.php?t=2818
https://techoverflow.net/blog/2015/09/09/accurate-short-long-delays-on-microcontrollers-using-chibios/

Currently wait functions are using `chThdSleepMicroseconds(us)` and this is not ideal, in particular, for converter which uses `wait_us()` in cretical timing to handle keyboard signals.
https://github.com/tmk/tmk_core/blob/e5f994033cbc8700745ac0c6d12772820492eed0/common/wait.h#L13-L15

Not fixed yet but I'll fix this in tmk_core later. Until then this patch would be very useful.

Thnaks

**Comment by belak** [comment]
Yeah, I've been using this all day today and haven't run into any problems yet.

**Comment by tmk** [comment]
without this patch what was your problem actually?
I never tried this firmware on real keyboard in fact.

**Comment by belak** [comment]
It's not a huge change, this just slightly improves the responsiveness of the keyboard. There's nothing particularly wrong without it.

**Pull request closed without merging**
